#!/bin/bash

############## get from Info.plist
function GetFromInfoPlist {
	exec < "$1"
	while read LINE; do
		if [ "$OLDLINE" == "<key>$2</key>" ]; then
			if [ "$3" == "string" ]; then
				TEMPVAR=${LINE#<string>}
				TEMPVAR=${TEMPVAR%</string>}
			elif [ "$3" == "integer" ]; then
				TEMPVAR=${LINE#<integer>}
				TEMPVAR=${TEMPVAR%</integer>}
			elif [ "$3" == "boolean" ]; then
				TEMPVAR=${LINE#<}
				TEMPVAR=${TEMPVAR%/>}
			fi
		fi
		OLDLINE="$LINE"
	done
	echo "$TEMPVAR"
}

MACOSFOLD="$(dirname "$0")"
SWMPREFIX="${MACOSFOLD%/*S}/Resources"
INFOPLISTFILE="${MACOSFOLD%/*S}/Info.plist"

######### Read Info.plist for all info needed from it
GAME_ID="$(GetFromInfoPlist "${INFOPLISTFILE}" "CFBundleName" "string")"
DESCNAME="$(GetFromInfoPlist "${INFOPLISTFILE}" "CFBundleDisplayName" "string")"
ENABLESUBS="$(GetFromInfoPlist "${INFOPLISTFILE}" "SVWEnableSubtitles" "boolean")"
FULLSCREENMODE="$(GetFromInfoPlist "${INFOPLISTFILE}" "SVWFullScreen" "boolean")"
GFXMODE="$(GetFromInfoPlist "${INFOPLISTFILE}" "SVWGFXMode" "string")"
LANGUAGE_ID="$(GetFromInfoPlist "${INFOPLISTFILE}" "SVWLanguage" "string")"
MUSIC_VOLUME="$(GetFromInfoPlist "${INFOPLISTFILE}" "SVWMusicVolume" "integer")"
SFX_VOLUME="$(GetFromInfoPlist "${INFOPLISTFILE}" "SVWSFXVolume" "integer")"
SPEECH_VOLUME="$(GetFromInfoPlist "${INFOPLISTFILE}" "SVWSpeechVolume" "integer")"
ASPECTRATIO="$(GetFromInfoPlist "${INFOPLISTFILE}" "SVWAspectRatio" "boolean")"

SAVEPATH="${SWMPREFIX}/saves"
GAMEPATH="${SWMPREFIX}/game"

if [ ! -f "${SAVEPATH}/.dontdeletethis" ]; then
	mkdir -p "${HOME}/Library/ScummvmSaveGame/${GAME_ID}" > /dev/null 2>&1
	/bin/ln -sfh "${HOME}/Library/ScummvmSaveGame/${GAME_ID}" "${SAVEPATH}" > /dev/null 2>&1
fi

if [ "${FULLSCREENMODE}" == "true" ]; then
	ADDITIONALPARAMS=" --fullscreen"
else
	ADDITIONALPARAMS=" --no-fullscreen"
fi

if [ "${ENABLESUBS}" == "true" ]; then
	ADDITIONALPARAMS="${ADDITIONALPARAMS} --subtitles"
fi

if [ -z "${GFXMODE}" ]; then
	ADDITIONALPARAMS="${ADDITIONALPARAMS} --gfx-mode=${GFXMODE}"
fi

if [ -z "${LANGUAGE_ID}" ]; then
	ADDITIONALPARAMS="${ADDITIONALPARAMS} --language=${LANGUAGE_ID}"
fi

if [ -z "${MUSIC_VOLUME}" ]; then
	ADDITIONALPARAMS="${ADDITIONALPARAMS} --music-volume=${MUSIC_VOLUME}"
fi

if [ -z "${SFX_VOLUME}" ]; then
	ADDITIONALPARAMS="${ADDITIONALPARAMS} --sfx-volume=${SFX_VOLUME}"
fi

if [ -z "${SPEECH_VOLUME}" ]; then
	ADDITIONALPARAMS="${ADDITIONALPARAMS} --speech-volume=${SPEECH_VOLUME}"
fi

if [ "${ASPECTRATIO}" == "true" ]; then
	ADDITIONALPARAMS="${ADDITIONALPARAMS} --aspect-ratio"
fi

echo "ScummvmWrapper: Starting ${DESCNAME}"
"${MACOSFOLD}/scummvm" --savepath="$SAVEPATH" --path="$GAMEPATH" $ADDITIONALPARAMS $GAME_ID
echo "ScummvmWrapper: Finished ${DESCNAME}"
